### ISSUE TITLE
ng8 not work

### ISSUE THREAD

**Issue by jiayisheji** [klemenoslaj/angular-demo-lazy-route-libraries#1]
Hello friend，Your idea is very cool, and I have been looking for a way to do this. Now I use it. I create a new route in the app to introduce the module in lib.

I used your method, but found that it didn't work in the ng8。

Since the ng8 lazy load routing has changed, the compilation I used was fine, but the browser runtime reported that the module could not be found.

**Comment by klemenoslaj** [comment]
@jiayisheji, yes angular 8 changed a bit that's why this unofficial solution doesn't work any more...they simply had no need to account for it.

I used this repo to point out to the Angular CLI team that this was possible with version 7, suspecting we might be close to an actual proper solution in the following comment:
https://github.com/angular/angular-cli/issues/6373#issuecomment-451512534

Not long after we received the reply with the official workaround, they as well locked the thread:
https://github.com/angular/angular-cli/issues/6373#issuecomment-453006158

Applying this a bit ugly workaround should fix your Angular 8 problems.

I as well updated README.md to avoid further confusion.

**Comment by jiayisheji** [comment]
@klemenoslaj The way I'm using it right now is by implementation [angular/angular-cli#6373 (comment)](https://github.com/angular/angular-cli/issues/6373#issuecomment-453006158), and this will switch perfectly to ng8. 

Ha-ha, if there is the latest news exchange together.

Thank you for your
